version: 0.2

env:
  variables:
    BUILD_DIR: "dist"                 # Vite default output
    S3_BUCKET: "smartorders-ui-host"   # override in CodeBuild env if needed
    DISTRIBUTION_ID: "E2UI4TB4374WI9"  # override in CodeBuild env
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci
  pre_build:
    commands:
      - echo "Ensure BUILD_DIR exists or run build"
  build:
    commands:
      - |
        if [ -d "$BUILD_DIR" ] && [ "$(ls -A $BUILD_DIR)" ]; then
          echo "Using existing $BUILD_DIR (prebuilt)"
        else
          echo "No prebuilt $BUILD_DIR — building now"
          npm run build
        fi
  post_build:
    commands:
      - echo "Syncing $BUILD_DIR to s3://$S3_BUCKET"
      - aws s3 sync "$BUILD_DIR/" "s3://$S3_BUCKET" --delete
      - echo "Invalidating CloudFront distribution $DISTRIBUTION_ID"
      - aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: $BUILD_DIR
